
services:

  streamlit:
    build: ./streamlit
    container_name: streamlit
    restart: always
    ports:
      - 8501

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - streamlit
